name: Send Outlook Email

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          secure: false
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Outlook Test"
          to: shaunak007@live.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hello,

This message is to inform you that your Defender Platinum subscription is scheduled for renewal based on your current account settings.

Renewal Date: February 11, 2026
Order Reference: XVCN984GF
Service Plan: Defender Platinum Suite (3-Year Plan)
Renewal Amount: $543.93
Billing Method: Automatic Debit

Service Information

The renewal will be processed automatically to ensure uninterrupted access to your service. No action is required if you wish to continue with the existing plan.

If you would like to review or update your subscription, or want to cancel before the renewal date, support assistance is available.

Customer Support: +1 (805) 505-2046*

If no changes are made prior to the scheduled renewal date, the service will continue under the current terms.

Thank you for choosing our services.

â€”
Customer Services
Support Line: +1 (805) 505-2046*
.
